package nuaa.ggx.pos.collector.soap.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import nuaa.ggx.pos.collector.soap.IWSTest;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-14T22:46:14.519+08:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "WSTestService", 
                  wsdlLocation = "file:/Users/riversye/Documents/myprojects/nuaacempos/src/main/webapp/WEB-INF/wsdl/sayHello.wsdl",
                  targetNamespace = "http://impl.soap.collector.pos.ggx.nuaa/") 
public class WSTestService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.soap.collector.pos.ggx.nuaa/", "WSTestService");
    public final static QName WSTestPort = new QName("http://impl.soap.collector.pos.ggx.nuaa/", "WSTestPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/riversye/Documents/myprojects/nuaacempos/src/main/webapp/WEB-INF/wsdl/sayHello.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSTestService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/riversye/Documents/myprojects/nuaacempos/src/main/webapp/WEB-INF/wsdl/sayHello.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSTestService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSTestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSTestService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WSTestService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WSTestService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WSTestService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IWSTest
     */
    @WebEndpoint(name = "WSTestPort")
    public IWSTest getWSTestPort() {
        return super.getPort(WSTestPort, IWSTest.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWSTest
     */
    @WebEndpoint(name = "WSTestPort")
    public IWSTest getWSTestPort(WebServiceFeature... features) {
        return super.getPort(WSTestPort, IWSTest.class, features);
    }

}
