
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package nuaa.ggx.pos.collector.soap;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-28T22:44:59.723+08:00
 * Generated source version: 3.1.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "CollectCommentService",
                      portName = "CollectCommentPort",
                      targetNamespace = "http://impl.soap.collector.pos.ggx.nuaa/",
                      wsdlLocation = "file:/Users/riversye/Documents/myprojects/nuaacempos/src/main/resources/wsdl/collectComment.wsdl",
                      endpointInterface = "nuaa.ggx.pos.collector.soap.ICollectComment")
                      
public class CollectCommentPortImpl implements ICollectComment {

    private static final Logger LOG = Logger.getLogger(CollectCommentPortImpl.class.getName());

    /* (non-Javadoc)
     * @see nuaa.ggx.pos.collector.soap.ICollectComment#collectComment(java.lang.String  url )*
     */
    public java.lang.Integer collectComment(java.lang.String url) { 
        LOG.info("Executing operation collectComment");
        System.out.println(url);
        try {
            java.lang.Integer _return = Integer.valueOf(342792425);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
