
package nuaa.ggx.pos.collector.soap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import nuaa.ggx.pos.collector.soap.impl.CollectCommentService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-28T22:44:59.619+08:00
 * Generated source version: 3.1.5
 * 
 */
public final class ICollectComment_CollectCommentPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.soap.collector.pos.ggx.nuaa/", "CollectCommentService");

    private ICollectComment_CollectCommentPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CollectCommentService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CollectCommentService ss = new CollectCommentService(wsdlURL, SERVICE_NAME);
        ICollectComment port = ss.getCollectCommentPort();  
        
        {
        System.out.println("Invoking collectComment...");
        java.lang.String _collectComment_url = "_collectComment_url954749258";
        java.lang.Integer _collectComment__return = port.collectComment(_collectComment_url);
        System.out.println("collectComment.result=" + _collectComment__return);


        }

        System.exit(0);
    }

}
