package nuaa.ggx.pos.collector.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-28T22:44:59.736+08:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://soap.collector.pos.ggx.nuaa/", name = "ICollectComment")
@XmlSeeAlso({ObjectFactory.class})
public interface ICollectComment {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "collectComment", targetNamespace = "http://soap.collector.pos.ggx.nuaa/", className = "nuaa.ggx.pos.collector.soap.CollectComment")
    @WebMethod
    @ResponseWrapper(localName = "collectCommentResponse", targetNamespace = "http://soap.collector.pos.ggx.nuaa/", className = "nuaa.ggx.pos.collector.soap.CollectCommentResponse")
    public java.lang.Integer collectComment(
        @WebParam(name = "url", targetNamespace = "")
        java.lang.String url
    );
}
