package nuaa.ggx.pos.collector.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-14T22:46:14.512+08:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://soap.collector.pos.ggx.nuaa/", name = "IWSTest")
@XmlSeeAlso({ObjectFactory.class})
public interface IWSTest {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://soap.collector.pos.ggx.nuaa/", className = "nuaa.ggx.pos.collector.soap.SayHello")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://soap.collector.pos.ggx.nuaa/", className = "nuaa.ggx.pos.collector.soap.SayHelloResponse")
    public java.lang.String sayHello(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );
}
