
package nuaa.ggx.pos.collector.soap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import nuaa.ggx.pos.collector.soap.impl.WSTestService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-14T22:46:14.390+08:00
 * Generated source version: 3.1.5
 * 
 */
public final class IWSTest_WSTestPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.soap.collector.pos.ggx.nuaa/", "WSTestService");

    private IWSTest_WSTestPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WSTestService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WSTestService ss = new WSTestService(wsdlURL, SERVICE_NAME);
        IWSTest port = ss.getWSTestPort();  
        
        {
        System.out.println("Invoking sayHello...");
        java.lang.String _sayHello_name = "_sayHello_name-203316089";
        java.lang.String _sayHello__return = port.sayHello(_sayHello_name);
        System.out.println("sayHello.result=" + _sayHello__return);


        }

        System.exit(0);
    }

}
