
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package nuaa.ggx.pos.collector.soap;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-14T22:46:14.499+08:00
 * Generated source version: 3.1.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "WSTestService",
                      portName = "WSTestPort",
                      targetNamespace = "http://impl.soap.collector.pos.ggx.nuaa/",
                      wsdlLocation = "file:/Users/riversye/Documents/myprojects/nuaacempos/src/main/webapp/WEB-INF/wsdl/sayHello.wsdl",
                      endpointInterface = "nuaa.ggx.pos.collector.soap.IWSTest")
                      
public class WSTestPortImpl implements IWSTest {

    private static final Logger LOG = Logger.getLogger(WSTestPortImpl.class.getName());

    /* (non-Javadoc)
     * @see nuaa.ggx.pos.collector.soap.IWSTest#sayHello(java.lang.String  name )*
     */
    public java.lang.String sayHello(java.lang.String name) { 
        LOG.info("Executing operation sayHello");
        System.out.println(name);
        try {
            java.lang.String _return = "_return1919085946";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
